### ISSUE TITLE
Job details getting committed in the Readme

### ISSUE THREAD

**Issue by prabhatkumarthakur** [mayadata-io/oep-e2e#191]
#### What needs to be done ? 

- The python script has to be written which will update the readme of corresponding job.
- This python script will take variables from pipeline job and should update the readme of the job.
-  In job  we have to add few variables i.e `job-id`,`stage`,`desc`,`time-stamp`,`job-result` which will  be passed to python script and then the python script will update the readme of corresponding jobs.

##### Take-A-Point :
- Changes required in repo [oep](https://github.com/mayadata-io/oep)  and [oep-e2e-gcp](https://github.com/mayadata-io/oep-e2e-gcp)

**Comment by amitbhatt818** [comment]
https://github.com/mayadata-io/oep-e2e/pull/193
https://github.com/mayadata-io/oep-e2e/pull/374/
