### ISSUE TITLE
[standup] q1 - e2e march week 2

### ISSUE THREAD

**Issue by amitbhatt818** [mayadata-io/oep-e2e#260]
This issue will consist of team plans w.r.t q1 e2e test cases after the introduction of TCID aka TestCaseID. A new comment can be started off by each team member & updated marking the progress of their tasks.

### Important Notes:
- TCID can be found from [master plan](https://github.com/mayadata-io/oep-e2e-gcp/blob/master/.master-plan.yml)
- Team leads will merge the one or more job yaml fragments into [.gitlab-ci.yml](https://github.com/mayadata-io/oep-e2e-gcp/blob/master/.gitlab-ci.yml)

**Comment by AmitKumarDas** [comment]
## Team Member AmitKumarDas
- P1 e2e testcase APIs
  - [x] recommendation api
  - _NOTE: API link will be a director setup & not a doc_
- P1 e2e testcases implementation
  - [ ] recommendation api _(will come up with PR)_
    - d-operators is the repo where some custom resources are being developed
    - these custom resources will be used to test recommendation api
    - these ensure we are able to run unit tests, integration tests before e2e tests
- P1 e2e README implementation
  - [ ] recommendation api _(will come up with PR)_
- P1 e2e stage/job implementation
  - [ ] recommendation api _(will come up with PR)_
- P1 e2e gitlab-ci.yml changes
  - [ ] recommendation api
  ```yaml  
  TODO
  ```

@AmitKumarDas is ensuring completion of cstor recommendation related e2e test cases

**Comment by amitbhatt818** [comment]
P1 - Add logic to execute install jobs in sequence **(PR RAISED Review Required)** https://github.com/mayadata-io/oep-e2e-gcp/pull/76/

**Comment by harshita-sharma011** [comment]
## Team Member Harshita Sharma
- [ ] Update teaming job names according to master.yml

**Comment by bhaskarhc** [comment]
## Team Member _Bhaskar_
- [ ] Display status of  Automated test cases (tcid Job's) in Doughnut Graphs . PR  raised https://github.com/mayadata-io/mdap-e2e-dashboard/pull/160 
- [ ] Change detail-pipeline-page  access  button  (doughnut) . [ working ]

**Comment by uditgaurav** [comment]
## Team Member Udit Gaurav
- **P1 e2e testcases implementation**

  - [ ]  [iuoi11] Install OpenEBS from valid custom docker registry (PR will be raised)
  - [x] [Add Openebs and node label cleanup stage in all openebs installation step](https://github.com/mayadata-io/oep-e2e/pull/250) **(PR Merged)**

- **P1 e2e readme implementation**

  - [ ]  [iuoi11] Install OpenEBS from valid custom docker registry (PR will be raised)

- **P1 e2e stage/job implementation**

  - [ ]   [iuoi11] Install OpenEBS from valid custom docker registry (PR will be raised)

- **P1 e2e gitlab-ci.yml changes**
  - [x] [Adding all openebs installation and openebs-upgrade pending jobs in gitlab-ci.yml](https://github.com/mayadata-io/oep-e2e-gcp/pull/77) **(PR Merged)**
  - [ ]  [iuoi06] Install openebs using custom resource limit (PR will be raised)
  ```yaml  
  TODO
  ```

**Comment by harshshekhar15** [comment]
## Team Member Harsh Shekhar

- Setting up gitlab pipeline on centOS based Rancher cluster.

**Comment by shiveshabhishek** [comment]
## Team Member Shivesh Abhishek
- Setting up Konvoy cluster with CentOS
