### ISSUE TITLE
metrics: gather prometheus related info to expose e2e metrics as prometheus metrics

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/oep-e2e#520]

**Comment by bhaskarhc** [comment]
@AmitKumarDas , is this issue for Grafana Dashboard ??

**Comment by AmitKumarDas** [comment]
yes @bhaskarhc 
I am working to expose these metrics.
If you have any expertise then you may set up the prometheus & grafana deployments in the pipelines.

**Comment by bhaskarhc** [comment]
For PipelineCoint vs perday graph i can do from ui .

**Comment by AmitKumarDas** [comment]
Does the UI understand prometheus metrics?

**Comment by bhaskarhc** [comment]
No , but i have pipeline detail history on Database . Using the DB data can construct the Graph .

**Comment by bhaskarhc** [comment]
previously i have a plan to make a day vs pipeline-ran-count graph . for that i created a endpoint 
```
https://oep-pipelines.mayadata.io/api/metrics?platform=rancher_pipelines&start='2020-06-01'&end='2020-06-06'
```

**Comment by AmitKumarDas** [comment]
@bhaskarhc IMO it will be better to move to a grafana based dashboard that is filled with prometheus metrics instead of having our own dashboard. 

Let me know your thoughts on above?

**Comment by AmitKumarDas** [comment]
Initial version can be found in e2e-metrics.
refer - https://github.com/mayadata-io/e2e-metrics/blob/master/deploy/doc.go
