### ISSUE TITLE
Unable to create mirror cstor pools using recommendations.

### ISSUE THREAD

**Issue by amitbhatt818** [mayadata-io/oep-e2e#523]
- We are attaching  `1 disk per node` for creating stripe cstor pools.
- But for creating mirror cstor pools we require minimum `2 disk per node`.
- And for creating raidz cstor pools we require minimum of `3 disk per node`.

- After increasing no of disks from 3 to 9 disks still we are unable to list mirror based recommendations. And I am able to list stripe based recommendations.
- After creating cstor-pools using recommendation pool pods are in `ImagePullBackOff` 

#### Pipeline link:
https://gitlab.mayadata.io/oep/oep-e2e-rancher/-/jobs/105711

**Comment by prabhatkumarthakur** [comment]
The below image is not present.
```
  Warning  Failed   5m3s (x657 over 160m)  kubelet, node3  Error: ImagePullBackOff
  Normal   BackOff  10s (x678 over 160m)   kubelet, node3  Back-off pulling image "mayadataio/cspi-mgmt:1.9.0-ee"
```

**Comment by AmitKumarDas** [comment]
This has been resolved
