### ISSUE TITLE
e2e-metrics should handle case-insensitive for calculation.

### ISSUE THREAD

**Issue by ajeshbaby** [mayadata-io/oep-e2e#525]
Guideline for team is to use ALL Caps for TCID-xxx-xxx-xx for creating TCID.

Use case of a manual error..  (Lets assume only 1 TCID in master and GITLab) Will it show 100% coverage or 0% coverage
TCID-ABC-DEF-GHI (Gitlabjob)
TCID-ABC-DEF-XYZ (master)

**Comment by AmitKumarDas** [comment]
@ajeshbaby it will show 0% as coverage

**Comment by AmitKumarDas** [comment]
https://github.com/mayadata-io/e2e-metrics/pull/9 will put all test case ids starting with tcid i.e. small cased as deprecated.
