### ISSUE TITLE
Director not consuming the OpenEBS EE version

### ISSUE THREAD

**Issue by ajeshbaby** [mayadata-io/oep-e2e#528]
As part of Director RC builds when we install OpenEBS it should install the OpenEBS-EE version.

**Comment by sagarkrsd** [comment]
This has been fixed by the below PRs:
https://github.com/mayadata-io/openebs-upgrade/pull/27
https://github.com/mayadata-io/openebs-upgrade/pull/28
https://github.com/mayadata-io/maya-io-server/pull/1838
https://github.com/mayadata-io/maya-io-server/pull/1839

**Comment by sagarkrsd** [comment]
![Screenshot from 2020-05-06 19-09-52](https://user-images.githubusercontent.com/31482140/81254681-71886d00-9049-11ea-9b40-eb1d01ca8821.png)

**Comment by prabhatkumarthakur** [comment]
Now it is present in 1.9.0-RC4. 
WE can close this issue.
