### ISSUE TITLE
Fix AWS loadbalancer issue for selenium grid

### ISSUE THREAD

**Issue by harshshekhar15** [mayadata-io/oep-e2e#529]
The selenium grid created in Rancher pipeline is in `ROLLBACK_COMPLETE` state. It shows the following issue while creating selenium grid for Rancher - 

![Screenshot from 2020-05-08 03-02-09](https://user-images.githubusercontent.com/40303207/81670140-d0dce780-9464-11ea-80fd-66245612eb07.png)

**Comment by AmitKumarDas** [comment]
> It seems to be working in AWS @rohan2794 & nik

**Comment by prabhatkumarthakur** [comment]
@AmitKumarDas  @ajeshbaby @harshshekhar15  Added the NAT rule to access the DOP from outside.
http://106.51.78.18:6026/login
