### ISSUE TITLE
Duplicate Jobs Running in pipeline

### ISSUE THREAD

**Issue by bhaskarhc** [mayadata-io/oep-e2e#538]
**Short Description:** 
- In one pipeline duplicate jobs running in same jobName and different jobID's . This will impact on mismatching of metrics .

**Issue Pipeline : **
https://oep-pipelines.mayadata.io/pipeline/e2e-test/10341/platform/rancher

**ScreenShot**
<img width="1436" alt="Screenshot 2020-05-12 at 10 53 27 AM" src="https://user-images.githubusercontent.com/40464957/81642558-4b940b80-9441-11ea-9c11-5ef8aae9b030.png">

**Both successful `e2e-metrics` job have Different metrics/logs **
<img width="1436" alt="Screenshot 2020-05-12 at 11 13 34 AM" src="https://user-images.githubusercontent.com/40464957/81642934-2bb11780-9442-11ea-952f-75f3a0160a76.png">

**Comment by harshshekhar15** [comment]
For debugging issues in the pipeline sometimes some jobs are cancelled and then re run due to which there are duplicate jobs present sometimes in the pipeline. It will not be present if there is no manual intervention in the pipeline.
