### ISSUE TITLE
AWS Pipeline Print K8s Version on `cluster-create` job .

### ISSUE THREAD

**Issue by bhaskarhc** [mayadata-io/oep-e2e#540]
**Description :**
Print k8s Version on `cluster-create` job . with the Prefix text **`KubernetesVersion :`**  .

**Similar issue solved for Rancher**
https://github.com/mayadata-io/oep-e2e/issues/522

**Comment by nrusinko** [comment]
Resolved and pushed to oep-release branch
![image](https://user-images.githubusercontent.com/10600138/81782746-f1f41580-9502-11ea-9c9a-5aee92bf20e0.png)
