### ISSUE TITLE
Unable to add all cstor-pool recommendation jobs / testcases

### ISSUE THREAD

**Issue by amitbhatt818** [mayadata-io/oep-e2e#543]
### What is the issue?

- We have multiple cstor pool recommendation test cases that needs to be executed into the cluster3 but we are not adding that in the gitlab-ci.yml because of which test case coverage is very low.

### What needs to be done 
- Cluster3 should be setup in the pipeline for Rancher with proper configuration.
- Disk should be added to the cluster in rancher
- And also we need to take this thing as priority to get coverage.

**Comment by ajeshbaby** [comment]
Let's target these into AWS for now. Since we have C3 cluster in AWS.
Rancher we can aim by early next week.

**Comment by AmitKumarDas** [comment]
Some of the testplans are running in AWS. Few are remaining.

**Comment by amitbhatt818** [comment]
All the test cases are added in AWS .
https://github.com/mayadata-io/oep-e2e-aws/pull/14/files

**Comment by AmitKumarDas** [comment]
@harshshekhar15 will add install testcases in rancher setup

**Comment by AmitKumarDas** [comment]
There were issues with connectivity to Cluster 3 . Once this is resolved cstor pool testcases will be integrated.

**Comment by AmitKumarDas** [comment]
blocked by https://github.com/mayadata-io/oep-e2e/issues/605

**Comment by prabhatkumarthakur** [comment]
Now it is unblocked from https://github.com/mayadata-io/oep-e2e/issues/605

**Comment by harshshekhar15** [comment]
The following PR resolves the above issue - https://github.com/mayadata-io/oep-e2e-rancher/pull/41
