### ISSUE TITLE
Functional tests are not running in AWS

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/oep-e2e#558]

**Comment by rohan2794** [comment]
@AmitKumarDas Are you talking about OpenEBS functional test cases ?

**Comment by gprasath** [comment]
This looks obsolete. @rohan2794 can you update and close if it works

**Comment by rohan2794** [comment]
OpenEBS Functional and Chaos tests  were implemented in  OEP-1.10  release itself for AWS platform.
cc: @gprasath
