### ISSUE TITLE
Rancher Platform OpenEBS Functional and Chaos Stabilization

### ISSUE THREAD

**Issue by ajeshbaby** [mayadata-io/oep-e2e#562]
-- Pumba is not working with default rancher
 -- Snapshot and Clone workflow
 -- Basic should be done by tomorrow OpenEBS Functional and Chaos ETA May19

**Comment by AmitKumarDas** [comment]
currently blocked by https://github.com/mayadata-io/oep-e2e/issues/605

**Comment by prabhatkumarthakur** [comment]
Now it is unblocked from issue https://github.com/mayadata-io/oep-e2e/issues/605
@gprasath  Is looking into this issue and update the same.

**Comment by gprasath** [comment]
All the functional jobs are passing.
Only one chaos job fails due to chaos injection tool used. I will look into this today.
![Screenshot from 2020-06-03 06-06-27](https://user-images.githubusercontent.com/32255588/83582886-6b11e600-a560-11ea-9121-c14a98708204.png)

**Comment by gprasath** [comment]
The chaos issue will be tracked under #651

**Comment by gprasath** [comment]
All the functional and chaos jobs added are successful.
![Screenshot from 2020-06-12 08-29-45](https://user-images.githubusercontent.com/32255588/84460221-030d7f00-ac87-11ea-8efd-68c64f6b0a68.png)
