### ISSUE TITLE
AWS Platform OpenEBS Functional and Chaos Stabilization

### ISSUE THREAD

**Issue by ajeshbaby** [mayadata-io/oep-e2e#563]
-- Basic should be done by tomorrow OpenEBS Functional and Chaos (ETA-May19)
 -- Snapshot and Clone

**Comment by AmitKumarDas** [comment]
waiting for @nrusinko to provide session to the team

**Comment by AmitKumarDas** [comment]
@gprasath  @amitbhatt818 to look into resolving this

**Comment by AmitKumarDas** [comment]
### updates
- all functional tests are passing
- there are some failures in chaos tests
- need active clusters with ssh connections
__ @gprasath / @nsathyaseelan

**Comment by AmitKumarDas** [comment]
### updates
- no new updates... @gprasath to put in details

**Comment by gprasath** [comment]
jiva-controller-kill job alone gets failed now. All the other functional and chaos jobs are passing. I will check and update shortly

**Comment by gprasath** [comment]
All the jobs under openebs functional and chaos stage are passing successfully.
https://gitlab.mayadata.io/oep/oep-e2e-aws/pipelines/11301
