### ISSUE TITLE
Refactor e2e metrics to cover all GUI test cases

### ISSUE THREAD

**Issue by rohan2794** [mayadata-io/oep-e2e#583]
We are merging multiple tests in a single TCID for GUI test cases. In these scenario e2e metric will give inappropriate or less coverage then expected. 
Reason for merging multiple tests into single TCID is that in GUI number of test cases are more and for every test cases we can't create separate Gitlab job otherwise there will be so many jobs like 100 or more in a single Gitlab stage.

**Comment by AmitKumarDas** [comment]
This assumes a low priority.
This will be taken up later.
