### ISSUE TITLE
Readme link should be replaced to test plan link from pipeline

### ISSUE THREAD

**Issue by amitbhatt818** [mayadata-io/oep-e2e#596]
- Here test case link is redirecting to readme.md of that particular test case.
- we need to change in to test plan link **i.e** https://e2e.mayadata.io/docs/director/openebs-provisioning/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST

![Screenshot from 2020-05-21 10-49-55](https://user-images.githubusercontent.com/33670159/82526202-06fb2500-9b51-11ea-8dc5-ce2d9acb9e28.png)

**Comment by ajeshbaby** [comment]
Lets print aboslute URL with each TC Job.

TC_E2E_PLAN_LINK=`https://e2e.mayadata.io/actuallink`

**Comment by amitbhatt818** [comment]
Raised PR for both the platforms 
**Aws:** https://github.com/mayadata-io/oep-e2e-aws/pull/23
**Rancher:** https://github.com/mayadata-io/oep-e2e-rancher/pull/28

**Comment by AmitKumarDas** [comment]
waiting for @bhaskarhc to get this done

**Comment by bhaskarhc** [comment]
#### Rancher TestCase jobs 
|  | Test case | URL |
|-|-----------|-------|
|<ul><li>- [ ] </li></ul> |cluster-create | NA
|<ul><li>- [ ] </li></ul> |cluster2-create | NA
|<ul><li>- [ ] </li></ul> |cluster3-create | NA
|<ul><li>- [ ] </li></ul> |TCID-DIR-INSTALL-ON-LOCAL-HP | NA
|<ul><li>- [ ] </li></ul> |selenium-grid-deploy | NA
|<ul><li>- [ ] </li></ul> |create-api-key | NA
|<ul><li>- [ ] </li></ul> |cluster-connect | NA
|<ul><li>- [ ] </li></ul> |client-components-check | NA
|<ul><li>- [ ] </li></ul> |cluster3-connect | NA
|<ul><li>- [ ] </li></ul> |client3-components-check | NA
|<ul><li>- [ ] </li></ul> |TCID-GUI-AUTH | NA
|<ul><li>- [ ] </li></ul> |TCID-GUI-CLUSTER | NA
|<ul><li>- [ ] </li></ul> |TCID-GUI-DASHBOARD | NA
|<ul><li>- [ ] </li></ul> |TCID-GUI-PROFILE | NA
|<ul><li>- [ ] </li></ul> |TCID-DIR-OP-INSTALL-OPENEBS | NA
|<ul><li>- [ ] </li></ul> |TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE | NA
|<ul><li>- [ ] </li></ul> |TCID-OPENEBS-POLICIES-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-APP-TARGET-AFFINITY | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-SNAPSHOT-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-VOLUME-SCALEUP | NA
|<ul><li>- [ ] </li></ul> |TCID-CSTOR-SNAPSHOT-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-CSTOR-CLONE-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-CSTOR-VOLUME-EXT4-RESIZE | NA
|<ul><li>- [ ] </li></ul> |TCID-CSTOR-VOLUME-XFS-RESIZE | NA
|<ul><li>- [ ] </li></ul> |TCID-LOCALPV-RANDOM-DEVICE-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-LOCALPV-SELECTED-DEVICE-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-LOCALPV-HOSTPATH-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-BUSYBOX-KILL | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-MULTIPLE-REPLICAS-FAILURE | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-REPLICA-NETWORK-DELAY | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-CONTROLLER-KILL | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-CONTROLLER-NETWORK-DELAY | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-REPLICA-NODE-AFFINITY | NA
|<ul><li>- [ ] </li></ul> |TCID-CSTOR-BUSYBOX-APP-KILL | NA
|<ul><li>- [ ] </li></ul> |TCID-CSTOR-TARGET-KILL | NA
|<ul><li>- [ ] </li></ul> |selenium-grid-cleanup | NA
|<ul><li>- [ ] </li></ul> |e2e-metrics | NA
|<ul><li>- [ ] </li></ul> |cluster-cleanup | NA
|<ul><li>- [ ] </li></ul> |cluster2-cleanup | NA
|<ul><li>- [ ] </li></ul> |cluster3-cleanup | NA

**Comment by bhaskarhc** [comment]
### AWS test Cases 
| | test case | url |
|--|----------|-----|
|<ul><li>- [ ] </li></ul> |cluster-create | NA
|<ul><li>- [ ] </li></ul> |TCID-DIR-INSTALL-ON-LOCAL-HP | NA
|<ul><li>- [ ] </li></ul> |selenium-grid-deploy | NA
|<ul><li>- [ ] </li></ul> |create-api-key | NA
|<ul><li>- [ ] </li></ul> |cluster-connect | NA
|<ul><li>- [ ] </li></ul> |client-components-check | NA
|<ul><li>- [ ] </li></ul> |cluster3-connect | NA
|<ul><li>- [ ] </li></ul> |client3-components-check | NA
|<ul><li>- [ ] </li></ul> |TCID-GUI-AUTH | NA
|<ul><li>- [ ] </li></ul> |TCID-GUI-CLUSTER | NA
|<ul><li>- [ ] </li></ul> |TCID-GUI-DASHBOARD | NA
|<ul><li>- [ ] </li></ul> |TCID-GUI-PROFILE | NA
|<ul><li>- [ ] </li></ul> |TCID-DIR-OP-INSTALL-OPENEBS | NA
|<ul><li>- [ ] </li></ul> |TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-STRIPE | NA
|<ul><li>- [ ] </li></ul> |TCID-OPENEBS-POLICIES-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-APP-TARGET-AFFINITY | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-SNAPSHOT-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-VOLUME-SCALEUP | NA
|<ul><li>- [ ] </li></ul> |TCID-CSTOR-SNAPSHOT-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-CSTOR-CLONE-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-CSTOR-VOLUME-EXT4-RESIZE | NA
|<ul><li>- [ ] </li></ul> |TCID-CSTOR-VOLUME-XFS-RESIZE | NA
|<ul><li>- [ ] </li></ul> |TCID-LOCALPV-RANDOM-DEVICE-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-LOCALPV-SELECTED-DEVICE-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-LOCALPV-HOSTPATH-CREATE | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-BUSYBOX-KILL | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-MULTIPLE-REPLICAS-FAILURE | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-REPLICA-NETWORK-DELAY | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-CONTROLLER-KILL | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-CONTROLLER-NETWORK-DELAY | NA
|<ul><li>- [ ] </li></ul> |TCID-JIVA-REPLICA-NODE-AFFINITY | NA
|<ul><li>- [ ] </li></ul> |TCID-CSTOR-BUSYBOX-APP-KILL | NA
|<ul><li>- [ ] </li></ul> |TCID-CSTOR-TARGET-KILL | NA
|<ul><li>- [ ] </li></ul> |selenium-grid-cleanup | NA
|<ul><li>- [ ] </li></ul> |e2e-metrics | NA
|<ul><li>- [ ] </li></ul> |cluster-cleanup | NA
