### ISSUE TITLE
Selenium Grid Optimisation

### ISSUE THREAD

**Issue by ajeshbaby** [mayadata-io/oep-e2e#610]
@nrusinko  -- Can you update the steps on how the Selenium Grid has been Setup.

- List down the optimization possible
- How to run parallel pipelines
- What's the limit of VMs it has to be run in a single pipeline
- How to scale based on need basis. 
- Also the cost aspect on scaling.

**Comment by nrusinko** [comment]
Raised a PR to fix the most of issues.
https://github.com/mayadata-io/oep-e2e-aws/pull/37

Fixes that was implemented:
- Move Selenium Grid setup job into **gui-automation** repo
- Update Selenium Grid yaml file so we will create separate VPC, Subnets
- Decrease number of nodes to be 30 
- Selenium Grid will be deployed in different regions for each project:
AWS - eu-north-1; Rancher - eu-west-1; Konvoy - eu-west-2
This will allow us to run 3 pipelines for each project without overlapping 

- This should be enough for now. In future if we want more parallel nodes we will have to increase Fargate limits
- After this PR approved I will make same changes for Konvoy and Rancher

**Comment by ajeshbaby** [comment]
Details of Selenium Grid in E2E pipelines 

- This uses fargate containers
-  Each platform selenium is created in different regions, as AWS has some limits(100 per each region)
- During a pipeline in `selenium-grid-deploy` job Selenium grid is created. 
- Currently, it will create 31 faragte containers(configurable), One hub(server) and 30 node(clients)  https://github.com/mayadata-io/gui-automation/tree/master/scripts/grid
-` grid-Publi-1RZZZ6Y9HL7S7-1120504501.eu-north-1.elb.amazonaws.com` Dynamic load  balancer is created, this will hub URL
- TC's that need to be executed will be sent hub and hub, in turn, distribute to the nodes. Hub will manage the queue. 
- And get destroyed at the end of the pipeline in the cleanup process. Which includes a selenium grid, load balancer

**Comment by AmitKumarDas** [comment]
Can we run selenium based tests without dependency on AWS?
Can we run selenium tests without the need for separate VMs?

**Comment by ajeshbaby** [comment]
Yes it is possible. We have the following options to run Seelnium Grid,

1. Selenium Grid on local. This would require a dedicated set of VMs
2. Selenium Grid on AWS which has 2 options.
 a. Selenium Grid with fargate (This is the option we are using)
 b. Selenium Grid with EC2 

What's the actual issue if we use FarGate, this is cheaper and dynamically created and destroyed.
