### ISSUE TITLE
Travis builds are failing

### ISSUE THREAD

**Issue by prabhatkumarthakur** [mayadata-io/oep-e2e#620]
The Travis build is failing after raising the PR with below error message
```
error @docusaurus/core@2.0.0-alpha.56: The engine "node" is incompatible with this module. Expected version ">=10.15.1"
```

**Comment by bhaskarhc** [comment]
Docusaurus have issue working on node 10.9.0 or below  .
- Travis Failing Issue solved by upgrading the node version (10.9.0 --> 10.16.0)
