### ISSUE TITLE
nodeType is null for nodes being labelled while installing openebs via Director

### ISSUE THREAD

**Issue by harshshekhar15** [mayadata-io/oep-e2e#632]
## Overview
DOP labels the nodes of the cluster with `mayadata.io/control-plane=true/false` and `mayadata.io/data-plane=true/false` in order to deploy openebs on the cluster. These labels determine whether data-plane or control-plane component will be deployed on that specific node or not.

## What's the issue?
After labelling the nodes and installing openebs on cluster3 in the test case - `TCID-DIR-OP-INSTALL-OPENEBS-DP-ON-SPECIFIC-NODE` still **nodeType** is null for the nodes of cluster3 in API.

![image](https://user-images.githubusercontent.com/40303207/83549103-64647e00-a522-11ea-96ff-f189a2ef86ef.png)

**Comment by harshshekhar15** [comment]
The following slack thread contains further details on the recent development towards debugging this issue - [nodeType discussion](https://mayadata-team.slack.com/archives/CNXSG793R/p1590658468168000)

**Comment by harshshekhar15** [comment]
**MOM of today's debugging session** --
- Change installation mode to advance in order to configure node selection in both CP and DP specific tests.
- There should no node labelling in case of basic installation.

**Comment by AmitKumarDas** [comment]
Test logic needs to be updated/changed to handle pipeline migration from basic to advanced install

**Comment by harshshekhar15** [comment]
The above issue has been fixed. The following PR's resolved the above issue -
- https://github.com/mayadata-io/oep-e2e/pull/636
- https://github.com/mayadata-io/oep-e2e/pull/637
