### ISSUE TITLE
Implement GUI based test for OpenEBS Install via Director

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/oep-e2e#681]

**Comment by prabhatkumarthakur** [comment]
@AmitKumarDas  In which cluster of the pipeline we will be running this test case. We have two modes of installation Basic and Advance. Which one should I prefer?

**Comment by prabhatkumarthakur** [comment]
@AmitKumarDas  I am closing this issue since we are doing this via API in pipeline
