### ISSUE TITLE
Implement cstor volume replica scaledown scenario.

### ISSUE THREAD

**Issue by gprasath** [mayadata-io/oep-e2e#690]

**Comment by w3aman** [comment]
This scenario  has been added to the piplines.
AWS: https://github.com/mayadata-io/oep-e2e-aws/pull/51
KONVOY: https://github.com/mayadata-io/oep-e2e-konvoy/pull/15
RANCHER: https://github.com/mayadata-io/oep-e2e-rancher/pull/48
