### ISSUE TITLE
Dmaas backup and restore MySQL [TCID-DIR-DMAAS-MYSQL]

### ISSUE THREAD

**Issue by rohan2794** [mayadata-io/oep-e2e#700]
Selenium test case to create dmaas backup of MySQL application deployed on cluster2 and restore the successful backup to cluster3 using AWS S3 bucket.

**Comment by bhaskarhc** [comment]
@rohan2794 , 
is mysql application present in the cluster ?? otherwise need to deploy the application by using code .

**Comment by rohan2794** [comment]
@bhaskarhc You need to deploy mysql application, don't depend on existing mysql if present.
You should install mysql on cluster2 in different namespace before running selenium test in pipeline.

**Comment by bhaskarhc** [comment]
https://gitlab.mayadata.io/oep/oep-e2e-aws/-/jobs/180321
TestCase successfully running in the pipeline , closing issue ..
