### ISSUE TITLE
GUI jobs failing due to multiple UI screen changes

### ISSUE THREAD

**Issue by rohan2794** [mayadata-io/oep-e2e#744]
In DOP `1.11.0-rc2.ee` release multiple GUI jobs are failing due UI screen changes pushed to RC2 build.
We need to  refactor the GUI code with current changes .

**Comment by bhaskarhc** [comment]
- Multiple GUI jobs failed because HTML labels or attribute change happens in some pages , because of that selenium code unable to find specific action buttons and input fields .

**Comment by rohan2794** [comment]
Cluster test was failing due to cluster name field attribute change
Teaming test case was failing because of Invite button attribute change.
Authentication test was failing due to Change Password button attribute change.
Dmaas tests were failing because introduction of Retention Count feature into screen and some other UI changes in Dmaas page
ref: https://github.com/mayadata-io/gui-automation/pull/40

**Comment by bhaskarhc** [comment]
### Stage : Director-Gui-Check
#### Job : TCID-DIR-TEAMING-USER-INVITE  , TCID-DIR-TEAMING-USER-ROLE-UPDATE-NEGATIVE

<img width="898" alt="Screenshot 2020-07-03 at 4 19 04 PM" src="https://user-images.githubusercontent.com/40464957/86462343-1ae99780-bd49-11ea-8625-c201d3e4b532.png">

#### Job : TCID-GUI-DASHBOARD

<img width="897" alt="Screenshot 2020-07-03 at 4 21 27 PM" src="https://user-images.githubusercontent.com/40464957/86462461-49677280-bd49-11ea-9691-88adb7934717.png">

### job : TCID-GUI-CLUSTER

<img width="899" alt="Screenshot 2020-07-03 at 4 22 44 PM" src="https://user-images.githubusercontent.com/40464957/86462602-787de400-bd49-11ea-9a3f-895ae2f95878.png">

### Job : TCID-DIR-DMAAS-CSTOR-NON-RESTIC , TCID-DIR-DMAAS-MINIO-DELETE , TCID-DIR-DMAAS-SCHD-CSTOR-AWS-BUCKET , TCID-DIR-DMAAS-SCHD-CSTOR-MINIO-BUCKET , TCID-DIR-DMAAS-SCHD-JIVA-AWS-BUCKET , TCID-DIR-DMAAS-SCHD-JIVA-MINIO-BUCKET , TCID-DIR-DMAAS-SCHD-JIVA-MYSQL-BUCKET , TCID-DIR-DMAAS-SCHD-LOCAL-HP-AWS-BUCKET , TCID-DIR-DMAAS-SCHD-LOCAL-HP-MINIO-BUCKET


```
Dmaas Jobs run as synchronous manner , 
- Some of the jobs got failed because of new input text box ( Retention count ) added in before clicking `schedule now` button .
- For Minio cloudprovider url field missing .
```
<img width="899" alt="Screenshot 2020-07-03 at 4 29 09 PM" src="https://user-images.githubusercontent.com/40464957/86463193-ab74a780-bd4a-11ea-9aeb-245aef85ae97.png">
