### ISSUE TITLE
Failing TCIDs in Konvoy

### ISSUE THREAD

**Issue by shiveshabhishek** [mayadata-io/oep-e2e#753]
I've found the following TCIDs getting failed on most of the pipelines in Konvoy as of now:

https://docs.google.com/spreadsheets/d/1KV8GlmQL4sjd9NnaI-365CIiOGSH_aOnfod1nxjdtqs/edit#gid=0

Also, most of the cases in the branch `OPENEBS-SETUP` are getting failed with similar message:

```
fatal: [127.0.0.1]: FAILED! => {"msg": "The task includes an option with an undefined variable. 
The error was: list object has no element 0\n\nThe error appears to be in '/litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-CREATE-RAIDZ/test.yml': line 77, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:\n\n        ## Fetch the deviceGroupName\n        - name: Fetch the deviceGroupName\n          ^ here\n"}
```

**Comment by amitbhatt818** [comment]
```TASK [Get BD] ******************************************************************
changed: [127.0.0.1] => {"changed": true, "cmd": "kubectl get bd -n openebs\n", "delta": "0:00:00.071525", "end": "2020-07-06 05:27:56.473694", "rc": 0, "start": "2020-07-06 05:27:56.402169", "stderr": "No resources found in openebs namespace.", "stderr_lines": ["No resources found in openebs namespace."], "stdout": "", "stdout_lines": []}
```
We don't have blockdevice in the cluster after installing openebs because of that pool creation jobs are getting failed
@shiveshabhishek @amitbhatt818

**Comment by amitbhatt818** [comment]
After looking into the issue with @shiveshabhishek we found that disks are not attached on cluster3 and because of that blokdevice is not getting created after openebs is installed.
Thread: https://mayadata-team.slack.com/archives/CNXSG793R/p1594018788155100?thread_ts=1594013862.142000&cid=CNXSG793R

**Comment by amitbhatt818** [comment]
Disks are attached in the cluster3 in rancher.
Fixed ref: https://github.com/mayadata-io/oep-e2e/issues/755

**Comment by amitbhatt818** [comment]
- `OPENEBS-SETUP` stage is fixed .
- `OPENEBS-FUNCTIONAL` and some of `DIRECTOR-GUI` check are failing.
cc: @shiveshabhishek
