### ISSUE TITLE
Openebs functional job is failing in Konvoy pipeline

### ISSUE THREAD

**Issue by amitbhatt818** [mayadata-io/oep-e2e#760]
- Openebs function job `TCID-CSTOR-VOLUME-EXT4-RESIZE` is failing in Konvoy

Job link: https://gitlab.mayadata.io/oep/oep-e2e-konvoy/-/jobs/168565

**Comment by w3aman** [comment]
This issue was just seen in only one pipeline. not seeing in other recent pipelines.
It was not any e2e-test bug neither from product side. in pipeline the test job pod was not picked up correctly.
