### ISSUE TITLE
cstor pool deletion test cases needs to be added in RANCHER

### ISSUE THREAD

**Issue by amitbhatt818** [mayadata-io/oep-e2e#792]
### List of test cases which are not present in RANCHER
- TCID-DIR-OP-DELETE-CSPC-WITH-VOLUME
- TCID-DIR-OP-DELETE-EXTERNAL-CSPC-WITH-NO-VOLUME
- TCID-DIR-OP-DELETE-SPC-WITH-VOLUME

You can refer to AWS pipeline for more details.

**Comment by harshshekhar15** [comment]
PR - https://github.com/mayadata-io/oep-e2e-rancher/pull/62
