### ISSUE TITLE
Need API doc to test api`s of DMaaS feature 

### ISSUE THREAD

**Issue by amitbhatt818** [mayadata-io/oep-e2e#793]
### Test cases I am working on :-
- TCID-DIR-DMAAS-SCHD-CSTOR-MINIO-BUCKET
- TCID-DIR-DMAAS-SCHD-CSTOR-AWS-BUCKET
- TCID-DIR-DMAAS-SCHD-CSTOR-GCP-BUCKET
 
### Basic requirement that should be present in API doc
- URL where we need to give post request
- Request body
- Expected response body.
- Flow of DMaaS schedule creation should be understood by the API doc.
- Any NOTE that should be taken care by Automation Engineer at the time of API testing.

**Comment by vishnuitta** [comment]
I need your help on this. Can we do this over a call where I can show you how to send requests and meaning of each API/parameter?
